### ISSUE TITLE
Implement bredcrumbs

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#1]
Implement breadcrumbs that shows where you are...

This should be implemented so that it's handled automatically by the theme. We shouldn't have to a piece of code on every page.

![breadcrumbs](https://cloud.githubusercontent.com/assets/902911/11262812/c7467cd4-8e94-11e5-8d5c-a8bb87270917.png)

**Comment by limikael** [comment]
COuld use some styling... :)

**Comment by limikael** [comment]
@ceciliaTunapanda Do you consider this resolved? If so, attach the "resolved" label and assign it to someone.

**Comment by limikael** [comment]
Cool... I would personally prefer if it was aligned to the save vertical line as tunapanda logo, the course/track introduction text and the tracks/swagpaths.

Also, make sure you pull the latest changes from the repo before you do `grunt ftpUploadTask`. I think I see that there is a change missing right now (Follow Swagpath and Visit Track should be capitalized)

**Comment by c3c1l1a** [comment]
Good feedback. Thanks. I did a pull but don't know why the changes were not reflected.

**Comment by limikael** [comment]
Oh sorry, it wasn't committed...

Looks good now, closing...
