### ISSUE TITLE
Ensure all pages works

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#10]

**Comment by limikael** [comment]
There are many tracks/swagpaths that are simply not implemented. Make sure they follow this form:

```
[course]
  [h5p-course-item id=""]
  [h5p-course-item id=""]
  ...
[/course]
```

**Comment by limikael** [comment]
This refers only to the site online, it does not refer to a local site. Because we are testing the content that lives on the live site. The content on the local  machine does not have this content.

**Comment by limikael** [comment]
Clicked around a bit to get a random sample, and it looks good to me, so closing!

**Comment by Johngitonga** [comment]
Ok. Go ahead and close it, I can always edit it if need arises.

Best regards!

Alt email(s):

gitonga@tunapanda.org

Cell: +254 720 130 432

Thanks!
