### ISSUE TITLE
Create tutorial course

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/TI-wp-content-theme#12]
Create a tutorial that shows:
- How to get an author account - please contact wp-authors@tunapanda.org
- How to upload/create H5P items (note: assume learner already knows how to create H5P items)
- How to assemble the H5P items into a swagpath
- How to create a description for the swagpath

**Comment by jaylarson85** [comment]
The text version of this is being stored in [CONTRIBUTE.md](https://github.com/tunapanda/TI-wp-content-theme/blob/master/CONTRIBUTE.md).

**Comment by jaylarson85** [comment]
It's [here](http://content.tunapanda.org/courses/knowledge-creation/creating-swagpaths-3/).

**Comment by limikael** [comment]
Oh sorry for the delay, it's awesome... closing...
