### ISSUE TITLE
Create p5js Swagpath

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/TI-wp-content-theme#16]
Create a swagpath that includes [Daniel Shiffman's awesome videos](https://www.youtube.com/channel/UCvjgXvBlbQiydffZU7m1_aw).

**Comment by jaylarson85** [comment]
As discussed, given the large number of videos this swagpath might itself best be a 6-7 swagpaths each with 4-8 videos and other exercises/materials organized by topic.

**Comment by Johngitonga** [comment]
Here is the link to the swagifacts http://learning.tunapanda.org/courses/coding/p5js-course/.
The swagifacts are not interactive and if the first issue looks good, close it and create another issue about making the swagifacts interactive.

**Comment by limikael** [comment]
Ok looks good! Closing...
