### ISSUE TITLE
Update the instructions in the README.md so they are easier to follow for new developers

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#18]
Remind developers that they need to activate the theme after downloading it.

**Comment by Johngitonga** [comment]
I have updated the file: have added some guidelines and some infographics to explain it visually.

**Comment by limikael** [comment]
We are trying to follow the following process... When an issue is done, attach the "resolved" label and assign it to someone else... It doesn't really matter who, as long as it is someone who you think is qualified to "test" the solution to the issue... And then that person checks so everything looks good, and then that person should close it...

**Comment by c3c1l1a** [comment]
Nice work
