### ISSUE TITLE
Sign up, log in

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#2]

**Comment by allaN254** [comment]
Sorry if I am not able to describe it well it is my first time to contribute to an issue. We need to have a way for new user to login and members to register. For example like it is in the picture below, 
![screenshot from 2015-11-25 12 45 11](https://cloud.githubusercontent.com/assets/10713649/11393877/55d0fd52-9373-11e5-9238-62aff831c915.png)
On this issue I have found a wordress plugin called [Baw-login-logou](https://wordpress.org/plugins/baw-login-logout-menu/) that enables to new user to register, login, and logout. Check out for testing then we can decide on the look or whether if it fits.
Also, another related thing to this is whether we should allow social login/signup as shown in, for example as shown below. I have also got another plugin called [Ultimate Member](https://wordpress.org/plugins/ultimate-member/) haven't tested functionality yet but I think it is also worth testing. 
![social login](https://cloud.githubusercontent.com/assets/10713649/11394083/31138bdc-9374-11e5-9b1c-6b5ddd931d0e.png)

**Comment by c3c1l1a** [comment]
The functionality part of the login is fine I would say but the styling needs a bit more.

**Comment by limikael** [comment]
I think it will do for now, we can open another issue about the design later... Please test it someone! Assigning you @jaylarson85, feel free to assign it to someone else for checking....

**Comment by limikael** [comment]
What is the problem?

**Comment by Johngitonga** [comment]
Registration goes through but still I cannot login with the credentials I used to sign up.

**Comment by mrlarso** [comment]
I tried signing up as both a user and as a wordpress admin. Didn't receive confirmation email on either occasion and can't login.

Question- Should this be 2 separate issues?

On password recovery (as user) received the error message:

**The email could not be sent.
Possible reason: your host may have disabled the mail() function.**

**Comment by limikael** [comment]
Yeah, open a new issue for the mail sending... I have some info on why it doesn't work, would be awesome with some research on what to do with it... Will write it in the new issue...

**Comment by limikael** [comment]
We can use this plugin to make the tabs stay: https://github.com/limikael/tabby-cookie

We should install it using github updater, but the plugin is not adapted to be used with that. It needs to have a "GitHub Plugin URI" in its description. A good way would be to fork the repo, put it under tunapanda and put that line in there, then install it using github updater.

For reference on how to use the "GitHub Plugin URI" field, see: 

https://github.com/tunapanda/wp-remote-sync/blob/master/wp-remote-sync.php

**Comment by mrlarso** [comment]
@johngitonga, can you please check to see if it's working now?

**Comment by limikael** [comment]
I tested and I saw that at least the tab is staying as it should!

**Comment by munga4** [comment]
The issue is resolved and its working.
