### ISSUE TITLE
Add a brief description of the swagpaths in the track's breadcrumbs

### ISSUE THREAD

**Issue by Johngitonga** [tunapanda/TI-wp-content-theme#21]
![description](https://cloud.githubusercontent.com/assets/13312294/11651618/3e708468-9da3-11e5-9bf8-d1166e000e04.png)

**Comment by limikael** [comment]
Just a note on terminology... We shouldn't call it "course", let's use the terms "track" and "swagpath"...

**Comment by Johngitonga** [comment]
Oh sorry! Forgive my ignorance

**Comment by limikael** [comment]
:)

**Comment by c3c1l1a** [comment]
I think it looks nice
