### ISSUE TITLE
Show completed swag on swagmap

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#25]
On the swagmap, the swag you have not yet collected should be shown as hollow circles, the swag you have collected should be filled in.

**Comment by limikael** [comment]
The easiest way to test this currently is to go to:

http://content.tunapanda.org/swagmap/

And then verify that all swag there renders as hollow circles. Then go to this swagpath:

http://content.tunapanda.org/courses/testing/how-are-you/

And complete it. Go back to the swagmap, and the "test" swag should now render as a filled in circle.

To understand why this swagpath provides the test swag, edit it by going to this link:

http://content.tunapanda.org/wp-admin/post.php?post=786&action=edit

And you will see "test" as the value for the provides custom field.

**Comment by limikael** [comment]
ok try again now! seems the wp-h5p-xapi plugin was not enabled on learning.tunapanda.org

**Comment by neerajkamdar** [comment]
I’m getting an error “Unable to save result data” when I select an option in the testing course with the message below.  

Message: {"error":true,"success":false,"message":["`[]` must be `object` not `array` in `statement.context.extensions`"],"code":400,"trace":"#0 \/var\/www\/learninglocker\/app\/locker\/repository\/Statement\/EloquentStorer.php(74): Locker\Helpers\Helpers::validateAtom(Object(Locker\XApi\Statement), 'statement')\n#1 \/var\/www\/learninglocker\/app\/locker\/repository\/Statement\/EloquentStorer.php(35): Locker\Repository\Statement\EloquentStorer->constructValidStatements(Array, Object(Locker\Repository\Statement\StoreOptions))\n#2 \/var\/www\/learninglocker\/app\/locker\/repository\/Statement\/EloquentRepository.php(31): Locker\Repository\Statement\EloquentStorer->store(Array, Array, Object(Locker\Repository\Statement\StoreOptions))\n#3 \/var\/www\/learninglocker\/app\/controllers\/xapi\/StatementStoreController.php(129): Locker\Repository\Statement\EloquentRepository->store(Array, Array, Array)\n#4 \/var\/www\/learninglocker\/app\/controllers\/xapi\/StatementStoreController.php(66): Controllers\xAPI\StatementStoreController->createStatements(Array)\n#5 \/var\/www\/learninglocker\/app\/controllers\/xapi\/StatementController.php(73): Controllers\xAPI\StatementStoreController->store(Array)\n#6 \/var\/www\/learninglocker\/app\/controllers\/xapi\/BaseController.php(45): Controllers\xAPI\StatementController->store()\n#7 [internal function]: Controllers\xAPI\BaseController->selectMethod()\n#8 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(231): call_user_func_array(Array, Array)\n#9 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('selectMethod', Array)\n#10 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\xAPI\StatementController), Object(Illuminate\Routing\Route), 'selectMethod')\n#11 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\xAP...', 'selectMethod')\n#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()\n#13 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(109): call_user_func_array(Object(Closure), Array)\n#14 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))\n#15 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))\n#16 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))\n#17 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))\n#18 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)\n#19 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)\n#20 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)\n#21 \/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)\n#22 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))\n#23 \/var\/www\/learninglocker\/public\/index.php(49): Illuminate\Foundation\Application->run()\n#24 {main}"}
Code: 400

**Comment by limikael** [comment]
yep i have seen that... damn... ok taking this back....

**Comment by limikael** [comment]
ok now, damnit!

**Comment by jaylarson85** [comment]
Nice!
