### ISSUE TITLE
Only show swagpaths that are on a "good" level

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#26]
By default, show only swagpaths that the user has all prerequisites for.

**Comment by limikael** [comment]
If you go into a track, such as:

http://learning.tunapanda.org/courses/testing/

It will only show the "How are you?" swagpath from the beginning (if you don't have the prerequisites for the other swagpaths), with an option to show the rest of the swagpaths.

If the "How are you?" is completed already, the other swagpaths will show as well...

It's a bit difficult to test, since there is no way to "uncomplete" a swag. Two ways to test it would be... 
1. Use a different user, that has not yet completed the "How are you?" swagpath.
2. Change the swag that "How are you?" provides and that "What are you doing?" requires.

**Comment by limikael** [comment]
http://learning.tunapanda.org is up again... Can you please check now @jaylarson85 ? Or have someone else do it...

**Comment by munga4** [comment]
Its look okay.
