### ISSUE TITLE
Show "warning" text for swagpaths that the user doesn't have the prerequisites for

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#27]
Suggest "To get the most out of this swagpath, consiter following ..., ... or ... first"

**Comment by limikael** [comment]
Ok implemented... Instructions for testing... First go to the swagmap, consider the chain:

"How are you?" --> first-test --> "What are you doing?" --> another-test

So, the "first-test" swag is a requirement for "What are you doing?". If you go to the "What are you doing?" swagpath, without first completing the "How are you?" swagpath:

http://learning.tunapanda.org/courses/testing/what-are-you-doing/

You should see the warning. If you complete the "How are you?" swagpath and go back to the "What are you doing?" the warning should disappear.

**Comment by jaylarson85** [comment]
It works!
