### ISSUE TITLE
Tickmark for completed swagifacts

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#3]

**Comment by limikael** [comment]
Currently, the course page looks like this:

![screenshot from 2015-11-30 09-00-17](https://cloud.githubusercontent.com/assets/902911/11465201/b42b475e-9747-11e5-826a-6760acbc36a4.png)

With the checkmarks, a suggested design is like this:

![screenshot from 2015-11-30 09-00-17 changed](https://cloud.githubusercontent.com/assets/902911/11465199/b1e6629e-9747-11e5-9614-ef15e1ca9689.png)

Things that need to be implemented:
- Show the title of the course just above the H5P content area.
- Move the tabs from the top to the left side.
- Inside the tabs, implement check marks that turns green if someone completes a court part.

How to implement the check marks:
- Implement a helper function that can answer true or false depending on if there exists a completed XAPI statement given a target url. The signature would look like:

``` php
  function isXapiStatementComplete($xapiTargetUrl) {
  }
```
- Implement a helper function that can give the target url given a H5P id. The signature would look like:

``` php
  function getXapiUrlByH5pId($h5pId) {
  }
```

Using the two functions, we can decide for each tab how it should be rendered.

**Comment by limikael** [comment]
This is implemented now, there is a test for it here:

http://content.tunapanda.org/courses/testing/how-are-you/

If you are logged in, complete that H5P and reload the page, there will be a tickmark.

On the way getting there, you will get some 500 internal server errors though... But that's a different issue...

**Comment by c3c1l1a** [comment]
I used the test link above but there is an error. Couldn't copy paste it but I took a screen shot. I don't know if that is the 500 internal server error you are referring to.  
![error](https://cloud.githubusercontent.com/assets/8858461/11812097/d341e184-a34a-11e5-993e-35dd99155a23.png)

**Comment by limikael** [comment]
aha...

in this case it is because the teacher user doesn't have a registered email... it only works if you are logged in and if you have a proper email address associated with the user...

but... it shoudn't give _that_ error, it looks bad... will fix...

**Comment by c3c1l1a** [comment]
Awesome works now.

**Comment by limikael** [comment]
But how could it, I haven't changed anything... :)

I think we have a bug if the user doesn't have an email registered, let me fix that...

**Comment by limikael** [comment]
After some investigation...

Yes there will be an error if the user doesn't have an email address. But on 2nd though, this is ok, since not having an email is kind of an "error" to begin with.

So closing for now...
