### ISSUE TITLE
Course Presentation Completion Problem

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/TI-wp-content-theme#33]
If you create a course presentation and disable the "summary slide," there is no xAPI "complete" statement generated when a user reaches the end of the presentation.

Also reference [here as an issue in an H5P repo](https://github.com/h5p/h5p-course-presentation/issues/16).

**Comment by limikael** [comment]
We'll focus on a workaround:

https://github.com/tunapanda/TI-wp-content-theme/issues/57

So closing this...
