### ISSUE TITLE
Break out swag functionality to a separate plugin

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#36]
We should put all the swag functionality, e.g. swagmaps, tracklisting, swagpaths, the swagpath h5p viewer, xapi communication, etc, into its own wordpress plugin. We should have a separate repository for this.

**Comment by c3c1l1a** [comment]
Plugin repository created at https://github.com/tunapanda/wp-swag

**Comment by limikael** [comment]
Great work!

Only thing remaining is to make it compatible with github updater...

**Comment by c3c1l1a** [comment]
Both the plugin and theme are compatible with github updater

**Comment by limikael** [comment]
:+1: awesome!
