### ISSUE TITLE
Export KPI:s for visualising swagpath status

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#39]
Exact KPI:s TBD.

**Comment by limikael** [comment]
I have created a plugin for aggregating information and present it for dasheroo:

https://github.com/tunapanda/wp-dasheroo-kpis

And I created a dasheroo dashboard here:

https://www.dasheroo.com/reports/948d32e0b2efce252151e379b0c99212/public

(link updated, it wasn't the public one before)

@EliasKinyua let's sit down and discuss if this is what you need and/or how it can be changed to become what you need.

**Comment by EliasKinyua** [comment]
Seems to be working as expected.
