### ISSUE TITLE
Page for badges for swag

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#4]

**Comment by Johngitonga** [comment]
![badge](https://cloud.githubusercontent.com/assets/13312294/11716960/50eacb14-9f5e-11e5-875b-4208dc1ff9e9.png)
Did you mean badges like this or what kind of badges can we create for that page?

**Comment by munga4** [comment]
Its looking good,  but we need to make it look good and clear.

**Comment by limikael** [comment]
Yes something like this... However, the important thing to know for someone who is going to implement this is not the design for the actual badge, but rather the overall design for the page where the badges go

**Comment by munga4** [comment]
![budge-1](https://cloud.githubusercontent.com/assets/8983198/11811993/16237766-a34a-11e5-8e23-0f5e57fd283e.png)

**Comment by munga4** [comment]
![Uploading budge-1.png…]()

**Comment by munga4** [comment]
This will welcome the student to the first test before he/she moves to next test.
![budge-1](https://cloud.githubusercontent.com/assets/8983198/11812220/a6816c0e-a34b-11e5-96c2-ee16cf3ed134.png)

**Comment by limikael** [comment]
Badges for collected swag is now shown under "My Account", under the "My Swag" tab.
