### ISSUE TITLE
Make it possible to earn swag by submitting work and having it reviewed

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#41]
Preferably this should be implemented as a usable Wordpress plugin (usable also outside swag, that is).

**Comment by limikael** [comment]
Have an RC now here: https://github.com/tunapanda/wp-deliverable

Next step is to integrate it into swag...

**Comment by limikael** [comment]
We have an initial version now, deployed on http://learning.tunapanda.org/

We should test that the following work:
- Assigning users to groups.
- Creating deliverables.
- Adding deliverables to swagpaths. Make sure they show up in the swagpath.
- Can someone submit work?
- Does the work submitted appear for review for the relevant groups?
- Is it possible to review and appove the work?
- When the work is approved, does the original user get swag for it?

**Comment by limikael** [comment]
For reference, this is a place where a deliverable is on a swagpath:

http://learning.tunapanda.org/courses/coding/using-functions/

**Comment by munga4** [comment]
All are working.
