### ISSUE TITLE
Swag map didn't show when I synchronized the learning.tunapanda  into my local server

### ISSUE THREAD

**Issue by Johngitonga** [tunapanda/TI-wp-content-theme#46]
There is a swagmap on the learning.tunapanda which didn't show on my localhost when I synced the site.

**Comment by limikael** [comment]
This is because the swagmap doesn't show unless the LRS is set up. This is somewhat unintuitive, we should make the swagmap work even without those settings.

**Comment by limikael** [comment]
Alright... Now it should work even if there are no xapi settings... Obviously no progress will be tracked or shown, but things does at least work...

**Comment by munga4** [comment]
Its working well.

**Comment by munga4** [comment]
Its working well.
