### ISSUE TITLE
Unable to access swagpath

### ISSUE THREAD

**Issue by allaN254** [tunapanda/TI-wp-content-theme#47]
Hello guys, when I clicked on the swagpath for entrepreneurship, this is the message I get, What should I do as the next step?
![login into entreprenuership swagpath](https://cloud.githubusercontent.com/assets/10713649/12881265/876e39bc-ce59-11e5-9c40-c64da175ef6b.png)

**Comment by limikael** [comment]
If you would log in and look at the source code for the page, you would find that it is not in accordance with what it should be. For reference for how it should look, see:

http://learning.tunapanda.org/courses/knowledge-creation/creating-swagpaths-3/

Coordinate with @munga4 as he is also on this case now...

**Comment by limikael** [comment]
@allaN254 do you have any further questions regarding this? If not, please close the issue.
