### ISSUE TITLE
Suggest swagpaths / feedback

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#53]
Create a feedback form where users can suggest new swagpaths or otherwise communicate with the "backend".

**Comment by c3c1l1a** [comment]
I installed the plugin usernoise for feedback. The plugin does not allow discussion for a given feedback/swagpath idea/feedback/question. I think this is important to have. Will checkout other plugins as well. Anyone who knows a good one to test out can leave a suggestion.

**Comment by limikael** [comment]
I think usernoise works well for a "sitewide" discussion, e.g. for general questions or to suggest new swagpaths...

Wordpress has a built in comments system. Maybe we can use that for the per-swagpath discussions?

https://en.support.wordpress.com/enable-disable-comments-for-future-posts-pages/

**Comment by c3c1l1a** [comment]
This issue very closely related to issue https://github.com/tunapanda/TI-wp-content-theme/issues/50. I think they should be merged.

**Comment by limikael** [comment]
I don't know if they are so closely related actually... I think that this issue is perfectly solved with the usernoise plugin as we do now. The other one is best solved with the built in post/page comments functionality in wordpress

**Comment by Johngitonga** [comment]
I have tested the plugin and it works really well. I'll now close the issue.
