### ISSUE TITLE
Download lesson plan improvement

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#54]
Lesson plans should not only be downloadable by people who have achieved the swag for the swagifact, but also by users with certain roles and/or capabilities.

Some research needs to be done on exactly how we should use the Roles and Capabilities API for this, more info on the API here:

https://codex.wordpress.org/Roles_and_Capabilities

**Comment by mrlarso** [comment]
How about if any user is either the page's author or has the capability to edit other authors' pages, then they can view/download the lesson plan?

**Comment by limikael** [comment]
:+1:
