### ISSUE TITLE
Find which H5P content crashes the upgrade to latest content type versions

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#56]
Currently we can't upgrade out H5P content to the latest version of the H5P content libraries. One of our H5P contents causes it to crash. We need to find which one it is, and the submit this to the H5P team as a bug.

The best way to find it I think would be using a manual "divide and conquer" method. I.e. on a local system, we delete half of the H5P content and see if the update works. Then we can eliminate half of the H5P contents, and then we continue like this until we find the one that crashes.

**Comment by munga4** [comment]
WordPress fixed the bug, It's working now.
