### ISSUE TITLE
Move mail api from Mandrill to another service.

### ISSUE THREAD

**Issue by neerajkamdar** [tunapanda/TI-wp-content-theme#61]
Mandrill is moving to paid accounts on Apr 27 and will no longer have a free tier. So we will have to find another email sending service and transition to them. Mailgun might be a good option.

**Comment by neerajkamdar** [comment]
I've added the Mailgun plugin and setup the Mailgun account. I've tested and seems to be working. If someone else could also test and verify that will be great.

**Comment by limikael** [comment]
assigning @mrlarso for testing... feel free to re-assign...
