### ISSUE TITLE
Show error message when lrs data is incorrect

### ISSUE THREAD

**Issue by mrlarso** [tunapanda/TI-wp-content-theme#63]
When there is incorrect LRS information in the wp-swag plugin, the 'my account' page shows a paragraph of text that isn't very useful. It should explain the problem and how to solve it.

![lrs_error](https://cloud.githubusercontent.com/assets/5390448/15387277/f01ff77a-1db4-11e6-9c02-f5a473eb438b.png)

**Comment by limikael** [comment]
This issue was moved to tunapanda/wp-swag#8
