### ISSUE TITLE
Badges page design is not good

### ISSUE THREAD

**Issue by mrlarso** [tunapanda/TI-wp-content-theme#64]
The badges page design needs to be improved. Badges should be descriptive of the activity completed, and should fit into the window.

See image for current setup.
![badges](https://cloud.githubusercontent.com/assets/5390448/15569263/e1229154-2338-11e6-90c5-867f1ca9895f.png)

**Comment by limikael** [comment]
This issue was moved to tunapanda/wp-swag#7
