### ISSUE TITLE
Ensure all content is interactive

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#9]
All the H5P content packages should have a way to be "completed" by the learner. E.g. a quiz or so at the end.

**Comment by Johngitonga** [comment]
I think it would be more efficient to do it track by track. Also; the issue should be edited to say "Ensure all swagpaths are interactive (for a specific track)" since we have over 100 swagpaths.

**Comment by limikael** [comment]
Moved to its own repo
